version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    test-api:
        description: 'Prettier & eslint checks; then start API server on localhost to run integration test'
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: yarn
                      - run: yarn eslint
                      - run: yarn prettier
                      - run: yarn start & (echo "Wait for 5 seconds for the server to start" && sleep 5 && echo "Starting test..." && yarn test)
    deploy-build:
        description: 'Trigger build and deploy with netlify build hook'
        docker:
            - image: cimg/base:2020.01
        steps:
            - run: $BUILD_HOOK

workflows:
    test-and-deploy:
        jobs:
            - test-api
            - deploy-build:
                  requires:
                      - test-api
                  filters:
                      branches:
                          only: master
